name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # Copy .env.test → .env so tests have default values
      - name: Setup client test env
        run: cp .env.test .env

      # Append secrets from GitHub Secrets into .env
      - name: Inject secrets into client .env
        run: |
          echo "SSL_KEY_FILE=${{ secrets.SSL_KEY_FILE }}" >> .env
          echo "SSL_CRT_FILE=${{ secrets.SSL_CRT_FILE }}" >> .env

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    services:
      mongodb:
        image: mongo:6
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # Copy .env.test → .env
      - name: Setup server test env
        run: cp .env.test .env

      # Append secrets
      - name: Inject secrets into server .env
        run: |
          echo "SSL_KEY_FILE=${{ secrets.SSL_KEY_FILE }}" >> .env
          echo "SSL_CRT_FILE=${{ secrets.SSL_CRT_FILE }}" >> .env

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
