name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # Copy .env.test → .env so tests have default values
      - name: Setup client test env
        run: cp .env.test .env

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # Copy .env.test → .env
      - name: Setup server test env
        run: cp .env.test .env

      - name: Install dependencies
        run: npm install

      - name: Run tests
        env:
          MONGOMS_VERSION: "7.0.14"
        run: npm test -- --testPathIgnorePatterns="https.test.ts"
